# Generated by Django 4.1.4 on 2022-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Рубрика')),
                ('slug', models.SlugField(unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Объявления', 'verbose_name_plural': 'Объявлении'},
        ),
        migrations.AlterField(
            model_name='product',
            name='contact_data',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
